title: Software Engineering
email: lester_lee@horacemann.org
description: >-
  This course will immerse students in the process of creating software and highlight how the field is one that walks a fine line between the creative and scientific. Students will engage in the study of building, designing, developing, maintaining and retiring software. In addition, students will learn how to visualize a product, explain their design to those with far less technical skill, and then work as a team to create the requested product. Students will engage in a year-long project, whose field of study will vary from year to year.

#Site settings
excerpt_length: 55

include: ['units']

#Build settings
markdown: kramdown
permalink: pretty
future: true